remote_theme: b2a3e8/jekyll-theme-console
title: "Annika Younge"
description: 'I'm Annika! I'm a sophomore at Stanford studying Data Science and Economics. I'm interested in signal and structure'
author: "Annika Younge"
url: "https://annikayounge.github.io"

header_pages:
  - index.md
  - about_me.md
  - education.md
  - cv.md
  - current_favs.md

style: light
listen_for_clients_preferred_style: true

footer: 'Contact me at <a href="mailto:ayounge@stanford.edu">ayounge@stanford.edu</a>'
markdown: kramdown
