remote_theme: "b2a3e8/jekyll-theme-console"
title: "Annika Younge"
description: "annika younge - mathematical and model engineering @ Stanford. current interests include causal inference, inequality, dynamics of information, machine learning, social and economic networks, model discovery, and model uncertainty."
author: "Annika Younge"
url: "https://annikayounge.github.io"

header_pages:
  - index.md
  - about_me.md
  - education.md
  - cv.md
  - current_favs.md

style: "light"
listen_for_clients_preferred_style: true

footer: 'Contact me at ayounge[at]stanford[dot]edu'
markdown: "kramdown"
