remote_theme: b2a3e8/jekyll-theme-console
title: "Annika Younge"
author: "Annika Younge"
url: "https://annikayounge.github.io"

header_pages:
  - index.md
  - about_me.md
  - education.md
  - cv.md
  - current_favs.md

style: light

footer: 'Contact me at <a href="mailto:ayounge@stanford.edu">ayounge@stanford.edu</a>'
markdown: kramdown
