remote_theme: "b2a3e8/jekyll-theme-console"
title: "Annika Younge"
description: "Rising junior at Stanford in B.S. Mathematical and Model Engineering. I'm interested in causal inference, inequality, dynamics of belief, machine learning, social and economic networks, and model uncertainty."
author: "Annika Younge"
url: "https://annikayounge.github.io"

header_pages:
  - index.md
  - about_me.md
  - education.md
  - cv.md
  - current_favs.md

style: "light"
listen_for_clients_preferred_style: true

footer: 'Contact me at ayounge[at]stanford[dot]edu'
markdown: "kramdown"
